app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('home');
});

Route::get('/home', function () {
    return view('home');
});

Route::resource('roles', 'RoleController');

Route::resource('cities', 'CityController');

Route::resource('users', 'UserController');

Route::resource('genres', 'GenreController');

Route::resource('instruments', 'InstrumentController');

Route::resource('performers', 'PerformerController');

Route::resource('musicalGroups', 'MusicalGroupController');

Route::resource('performerByGroups', 'PerformerByGroupController');

Route::resource('concerts', 'ConcertController');

app/Models/MusicalGroup.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="MusicalGroup",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="description",
 *          description="description",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="image_url",
 *          description="image_url",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="genre_id",
 *          description="genre_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="city_id",
 *          description="city_id",
 *          type="integer",
 *          format="int32"
 *      )
 * )
 */
class MusicalGroup extends Model
{
    use SoftDeletes;

    public $table = 'musical_group';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'name',
        'description',
        'image_url',
        'genre_id',
        'city_id',
        'deleted_at'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'description' => 'string',
        'image_url' => 'string',
        'genre_id' => 'integer',
        'city_id' => 'integer',
        'deleted_at' => 'datetime'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * Get the city record associated with the musical group.
     */
    public function city()
    {
        return $this->belongsTo('App\Models\City');
    }

    /**
     * Get the genre record associated with the musical group.
     */
    public function genre()
    {
        return $this->belongsTo('App\Models\Genre');
    }

    /**
     * Get the performers records associated with the musical group.
     */
    public function performers()
    {
        return $this->hasMany('App\Models\Performer');

    }       
}

app/Http/Controllers/MusicalGroupController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\CreateMusicalGroupRequest;
use App\Http\Requests\UpdateMusicalGroupRequest;
use App\Repositories\MusicalGroupRepository;
use App\Http\Controllers\AppBaseController as InfyOmBaseController;
use App\Http\Controllers\Utils;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class MusicalGroupController extends InfyOmBaseController
{
    /** @var  MusicalGroupRepository */
    private $musicalGroupRepository;
    private $utils;

    public function __construct(MusicalGroupRepository $musicalGroupRepo)
    {
        $this->musicalGroupRepository = $musicalGroupRepo; 
        $this->utils = new Utils();               
    }

    /**
     * Display a listing of the MusicalGroup.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->musicalGroupRepository->pushCriteria(new RequestCriteria($request));
        $musicalGroups = $this->musicalGroupRepository->all();

        return view('musicalGroups.index')
            ->with('musicalGroups', $musicalGroups);
    }

    /**
     * Show the form for creating a new MusicalGroup.
     *
     * @return Response
     */
    public function create()
    {                   
        return view('musicalGroups.create')
            ->with('cities', $this->utils->getAllCities()) 
            ->with('genres', $this->utils->getAllGenres());            
    }

    /**
     * Store a newly created MusicalGroup in storage.
     *
     * @param CreateMusicalGroupRequest $request
     *
     * @return Response
     */
    public function store(CreateMusicalGroupRequest $request)
    {        
        $input = $request->all();
        $filePath = "http://localhost/musicalfestival/public/assets/images/musicalgroups/";

        if($request->hasFile('image_url')) {
            $file = $request->file('image_url');
            $name = $file->getClientOriginalName();                                
            $file->move(public_path().'/assets/images/musicalgroups/', $name);

            $input['image_url'] = $filePath . $name;
        }

        $musicalGroup = $this->musicalGroupRepository->create($input);        

        Flash::success('MusicalGroup saved successfully.');

        return redirect(route('musicalGroups.index'));
    }

    /**
     * Display the specified MusicalGroup.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $musicalGroup = $this->musicalGroupRepository->findWithoutFail($id);

        if (empty($musicalGroup)) {
            Flash::error('MusicalGroup not found');

            return redirect(route('musicalGroups.index'));
        }

        return view('musicalGroups.show')->with('musicalGroup', $musicalGroup);
    }

    /**
     * Show the form for editing the specified MusicalGroup.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $musicalGroup = $this->musicalGroupRepository->findWithoutFail($id);

        if (empty($musicalGroup)) {
            Flash::error('MusicalGroup not found');

            return redirect(route('musicalGroups.index'));
        }

        return view('musicalGroups.edit')->with('musicalGroup', $musicalGroup);
    }

    /**
     * Update the specified MusicalGroup in storage.
     *
     * @param  int              $id
     * @param UpdateMusicalGroupRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMusicalGroupRequest $request)
    {
        $musicalGroup = $this->musicalGroupRepository->findWithoutFail($id);

        if (empty($musicalGroup)) {
            Flash::error('MusicalGroup not found');

            return redirect(route('musicalGroups.index'));
        }

        $musicalGroup = $this->musicalGroupRepository->update($request->all(), $id);

        Flash::success('MusicalGroup updated successfully.');

        return redirect(route('musicalGroups.index'));
    }

    /**
     * Remove the specified MusicalGroup from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $musicalGroup = $this->musicalGroupRepository->findWithoutFail($id);

        if (empty($musicalGroup)) {
            Flash::error('MusicalGroup not found');

            return redirect(route('musicalGroups.index'));
        }

        $this->musicalGroupRepository->delete($id);

        Flash::success('MusicalGroup deleted successfully.');

        return redirect(route('musicalGroups.index'));
    }    
    
}

resources/views/musicalGroups/create.blade.php
@extends('layouts.app')

@section('content')
    <section id="contact">        
        <div class="contact-section" style="padding-top:140px">
            <div class="ear-piece">
                <img class="img-responsive" src="images/ear-piece.png" alt="">
            </div>
            <div class="container">
                <div class="row">                    
                    <div class="col-sm-12">
                        <div id="contact-section">
                            <h2>Create Musical Group</h2>
                            <div class="status alert alert-success" style="display: none"></div>
                            @include('core-templates::common.errors')
                            <div id="main-contact-form" class="contact-form">
                                {!! Form::open(['route' => 'musicalGroups.store', 'files'=>true]) !!}

                                    @include('musicalGroups.fields')

                                {!! Form::close() !!}                                
                            </div>        
                        </div>
                    </div>
                </div>
            </div>
        </div>      
    </section>
    <!--/#contact-->
@endsection

resources/views/musicalGroups/edit.blade.php
@extends('layouts.app')

@section('content')
        <div class="row">
            <div class="col-sm-12">
                <h1 class="pull-left">Edit MusicalGroup</h1>
            </div>
        </div>

        @include('core-templates::common.errors')

        <div class="row">
            {!! Form::model($musicalGroup, ['route' => ['musicalGroups.update', $musicalGroup->id], 'method' => 'patch']) !!}

            @include('musicalGroups.fields')

            {!! Form::close() !!}
        </div>
@endsection

resources/views/musicalGroups/fields.blade.php
<div class="form-group">    
    {!! Form::text('name', null, ['class' => 'form-control', 'placeholder'=>'Nombre']) !!}
</div>
<div class="form-group">
    {!! Form::textarea('description', null, ['class' => 'form-control', 'rows' => '5', 'placeholder'=>'Descripción']) !!}
</div>
<div class="form-group">
    {!! Form::file('image_url', ['class' => 'form-control', 'style' => 'background:none;border:none']) !!}
</div>
<div class="form-group">
    {!! Form::select('genre_id', $genres, 1, ['class' => 'form-control']) !!}    
</div>
<div class="form-group">
    {!! Form::select('city_id', $cities, 1, ['class' => 'form-control']) !!}    
</div>                        
<div class="form-group">    
    {!! Form::submit('Save', ['class' => 'btn btn-primary pull-right']) !!}
    <a href="{!! route('musicalGroups.index') !!}" class="btn btn-primary">Cancel</a>
</div>

resources/views/musicalGroups/index.blade.php
@extends('layouts.app')

@section('content')
	<section id="event">
	    <div class="container" style="padding-top:180px">
	    	<!--<div class="row">
	    		<div class="col_sm_12">
	    			<div class="dropdown">
					  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
					    Grupos por region
					    <span class="caret"></span>
					  </button>
					  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
					    <li><a href="#">Action</a></li>
					    <li><a href="#">Another action</a></li>
					    <li><a href="#">Something else here</a></li>
					    <li role="separator" class="divider"></li>
					    <li><a href="#">Separated link</a></li>
					  </ul>
					</div>
	    		</div>
	    	</div>-->
	        <div class="row">
	            <div class="col-sm-12 col-md-9">
	                <div id="event-carousel" class="carousel slide" data-interval="false">
	                    <h2 class="heading">Musical Groups</h2>
	                    <a class="btn btn-primary pull_right" href="{!! route('musicalGroups.create') !!}">Add New</a>
	                                        
	                    <a class="even-control-left" href="#event-carousel" data-slide="prev"><i class="fa fa-angle-left"></i></a>
	                    <a class="even-control-right" href="#event-carousel" data-slide="next"><i class="fa fa-angle-right"></i></a>
	                    @include('musicalGroups.table')
	                </div>
	            </div>
	            <div class="guitar">
	                <img class="img-responsive" src="http://localhost/musicalfestival/public/assets//images/guitar.png" alt="guitar">
	            </div>
	        </div>          
	    </div>
	</section><!--/#event-->

@endsection

resources/views/musicalGroups/show.blade.php
@extends('layouts.app')

@section('content')
	<section id="about">
		<div class="container" style="margin-top:180px">	        
		@include('musicalGroups.show_fields')
		</div>
	</section><!--/#about-->
@endsection

resources/views/musicalGroups/show_fields.blade.php
<div class="row">
    <div class="col-sm-12 col-md-6 guitar2">               
        <img class="img-responsive" src="{!! $musicalGroup->image_url !!}" alt="guitar">
    </div>
    <div class="col-sm-12 col-md-6">
        <div class="about-content">                 
            <h2>{!! $musicalGroup->name !!}</h2>
            <p>{!! $musicalGroup->description !!}</p>
            <h2>Members</h2>            
            <div class="list-group">
                @foreach($musicalGroup->performers as $performer)
                    <div href="#" class="list-group-item">
                        <h3 class="list-group-item-heading">{!!$performer->name!!}</h3>
                        <h4 class="list-group-item-text">Instrument: {!!$performer->instrument->name!!}</h4>
                    </div>
                @endforeach                
            </div>
            <a class="btn btn-primary pull_right" href="{!! route('performers.create') !!}">Add New</a>                    
        </div>          
    </div>
</div>

resources/views/musicalGroups/table.blade.php
<div class="carousel-inner">
    <?php
        for($i=0; $i < count($musicalGroups); $i++){
            $mod = $i % 3;
            $routeShow = route('musicalGroups.show', [$musicalGroups[$i]->id]);

            if(($i !== 0) && ($mod === 0)){
                echo('
                        </div>
                    </div>');
            }

            if(($i === 0) || ($mod === 0)) {
                $class = ($i === 0) ? "item active" : "item";
                echo('
                    <div class="' . $class .'">
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="single-event">
                                    <a href=" '. $routeShow .'">
                                        <img class="img-responsive" src="'. $musicalGroups[$i]->image_url .'" alt="event-image">
                                    </a>
                                    <h4>' . $musicalGroups[$i]->name . '</h4>
                                    <h5>' . $musicalGroups[$i]->genre->name . '</h5>
                                    <h6>' . $musicalGroups[$i]->city->name . '</h6>
                                </div>
                            </div>
                    ');
            } else {
                echo('
                    <div class="col-sm-4">
                        <div class="single-event">
                            <a href=" '. $routeShow .'">
                                <img class="img-responsive" src="'. $musicalGroups[$i]->image_url .'" alt="event-image">
                            </a>
                            <h4>' . $musicalGroups[$i]->name . '</h4>
                            <h5>'. $musicalGroups[$i]->genre->name . '</h5>
                            <h6>' . $musicalGroups[$i]->city->name . '</h6>
                        </div>
                    </div>
                    ');
            }

            if($i === count($musicalGroups) -1){
                echo('
                        </div>
                    </div>');
            }        
        }
    ?>
</div>

<!--<table class="table table-responsive" id="musicalGroups-table">
    <thead>
        <th>Name</th>
        <th>Description</th>
        <th>Image Url</th>
        <th>Genre Id</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Deleted At</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($musicalGroups as $musicalGroup)
        <tr>
            <td>{!! $musicalGroup->name !!}</td>
            <td>{!! $musicalGroup->description !!}</td>
            <td>{!! $musicalGroup->image_url !!}</td>
            <td>{!! $musicalGroup->genre_id !!}</td>
            <td>{!! $musicalGroup->created_at !!}</td>
            <td>{!! $musicalGroup->updated_at !!}</td>
            <td>{!! $musicalGroup->deleted_at !!}</td>
            <td>
                {!! Form::open(['route' => ['musicalGroups.destroy', $musicalGroup->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('musicalGroups.show', [$musicalGroup->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('musicalGroups.edit', [$musicalGroup->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>-->